## Smart contracts shoould be 
* Simple
* Reliable
  * one way to make the contract reliable:
    require that the size of the array is less than some fixed number(put an upper bound to it)
    在函数声明后给参数加一个上限
* Predictable
### Enum

用借书的过程来理解。

![image-20220615210012898](C:\Users\Yang\AppData\Roaming\Typora\typora-user-images\image-20220615210012898.png)

在order已经shipper的时候不能取消

可以用enum这一datatype来模拟这一过程。

如果想要转移一个状态，需要通过一个新的函数来实现。

### Struct

What's KVM(key-value-mapping) in Solidity?

>![image-20220617204244877](C:\Users\Yang\AppData\Roaming\Typora\typora-user-images\image-20220617204244877.png)

What's a getter function in Solidity？

>对于所有public的状态变量，solidity都自动为状态变量生成了对应的getter（访问器）特性。

此函数与变量同名。

* 以internal访问时，按状态变量的方式使用
* 以external的方式访问时，则要通过访问器函数

```solidity
pragma solidity ^0.8.0;

contract AccessGetter{
  uint public data = 10;

  function f() returns (uint, uint){
    //分别以internal,external的方式访问
    return (data, this.data());
  }
}
```

在合约内可以直接操作，但在合约外只能用data（）来访问。

注意：在合约内，不能直接访问data()，因为访问器的函数可见性是external


### Functions
* Restrictions on public function i/o
    不能使用：{}map
            [][]多维数组(unfixed size)
    同时不能使用任意大小的数字（Arbitrary Size Number）  因为gas太贵

Solidity编译一个返回数组的函数时没有问题，但最好不要写一个不受控制的数组，因为这样的话如果有另一个合约想要得到该合约的返回值的话，就会失败。
* Returning multiple outputs
  调用的时候可以省略不必要的参数。
  

### Errors
>Solidity uses state-reverting exceptions to handle errors

Errors will undo all of the changes that we make in the current call.

#### Panic and Error

The built-in errors `Error(string)` and `Panic(uint256)` are used by the special functions. 

`Error` is used for “regular” error conditions while `Panic` is used for errors that should not be present in bug-free code.

#### assert and require

这两个便捷函数([ convenience functions](https://en.wikipedia.org/wiki/Convenience_function))assert和require可以用来检查必需的条件，如果不符合要求则会抛出一个异常(exception)

#### 两者抛出的异常有何区别？

assert函数会抛出panic类型的异常，而且我们应当只用它来检查不变的量(invariants)和内部的错误（internal errors）。正常运行的代码永远不应产生一个panic类型的数据，即使是有无效的外部输入。语义分析工具可以帮你规避此类错误。

当因assert报错的时候会用光你的所有gas

用时钟转一圈回到原点来理解unsigned integer的错误，上溢or下溢，即x+2^256=x

if x+y>=x  then x+y  does not overflow

 

require函数产生的错误比较奇怪，既不带数据（error without any data），也不属于Error类型"not an error of type Error(string)"。

通常用require来确保一些只有到了execution time 才能检测到的有效条件，通常包括输入中的条件or来自调用外部合约的返回值

```solidity
require(condition,errorMessage)
```



An `Error(string)` exception or an exception without data通常会在编译器遇到下列情况时产生：

* require(value) when value is false 
* use revert() or revert("description")
* 执行一个调用空合约（contract that contains no code）的外部函数的时候
* 当你的合约通过一个没有payable标识符的函数来接收以太的时候
* 当你的合约通过一个public getter function 来获取以太的时候

#### revert statement

```solidity
if(xxx){

revert("Error!")
//will create an Error(string)error 
}
//或者不加参数也行,由于向后兼容的原因
revert()
```



### try/catch statement(introduced in 0.6.0)

We can use a try/catch statement to catch a failure in an external call

#### 总结：

* Assert
  * Should Never Fail
  * Use up all gas
* Require
  * Validate inputs,preconditions and outputs
  * Does not use up all gas
* Revert
  * only throw up  error conditions
  * more useful when checking complex conditions